services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - files-network

  redis:
    image: redis:latest
    container_name: redis-container
    command: ["redis-server", "--requirepass", ${REDIS_INITDB_PASSWORD}]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - files-network

networks:
  files-network:
    driver: bridge

volumes:
  mongodb-data:
  redis-data:
