name: files-manager-app

services:
  api:
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    container_name: files-api
    restart: unless-stopped
    ports:
      - "5232:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URL=mongodb://admin:admin_password@mongodb:27017/files_db?authSource=admin
      - REDIS_URL=redis://:redis_password@redis:6379
      - STORAGE_DIR=/data/storage
    volumes:
      - files-storage:/data/storage
    depends_on:
      - mongodb
      - redis
    networks:
      - files-network

  webapp:
    build:
      context: ..
      dockerfile: docker/webapp.Dockerfile
    container_name: files-webapp
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - files-network

  mongodb:
    image: mongo:latest
    container_name: files-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin_password
      - MONGO_INITDB_DATABASE=files_db
    volumes:
      - mongodb-data:/data/db
    networks:
      - files-network

  redis:
    image: redis:7.4-alpine
    container_name: files-redis
    restart: unless-stopped
    command: ["redis-server", "/etc/redis/redis.conf"]
    environment:
      REDIS_PASSWORD: redis_password
    user: redis
    volumes:
      - redis-data:/data
      - ./configs/redis.conf:/etc/redis/redis.conf:ro
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 100M
    networks:
      - files-network

networks:
  files-network:
    driver: bridge

volumes:
  mongodb-data:
  redis-data:
  files-storage:
