# Stage 1: Build the React App
FROM node:22.13.1 AS build

WORKDIR /app
WORKDIR /usr/src/app/web
COPY web-app/package*.json ./
RUN npm install
COPY web-app ./
RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:latest
COPY --from=build /usr/src/app/web/dist /usr/share/nginx/html
EXPOSE ${WEB_PORT}
CMD ["nginx", "-g", "daemon off;"]
